name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --add-data "DejaVuSans.ttf;." --hidden-import=barcode --hidden-import=barcode.writer barcode_app_preview.py
    
    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: barcode-generator-windows
        path: dist/*.exe
